# Generated by Django 5.2.5 on 2025-08-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepurchase',
            name='purchased_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-12-12'),
            preserve_default=False,
        ),
    ]
