# Generated by Django 5.2.5 on 2025-08-19 16:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_coursepurchase_purchased_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursepurchase',
            unique_together={('student', 'course')},
        ),
    ]
