# Generated by Django 5.2.5 on 2025-09-10 16:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_coursepurchase_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
