# Generated by Django 5.2.5 on 2025-09-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepurchase',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='PENDING', max_length=20),
        ),
    ]
