# Generated by Django 5.2.5 on 2025-09-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_coursepurchase_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursepurchase',
            name='tran_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
